trigger:
- master

pool:
  name: trial_pool

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure subs'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
    
      echo "Running Terraform..."
      cd $(System.DefaultWorkingDirectory)/terraform 
      terraform init
      terraform apply -auto-approve
